[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
bincode = "1.3.3"
serde = "1.0"
serde_derive = "1.0.193"

[[bin]]
name = "server"
path = "src/main.rs"
