[package]
name = "lesson-11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server = { path = "server" }
client = { path = "client" }
csv = "1.3.0"
flume = "0.11.0"
slug = "0.1.4"
